version: 2

backends:
  backup-hdd:
    type: local
    path: /mnt/backup/restic-backups
    key: ${RESTIC_PASSWORD}

global:
  hooks:
    prevalidate:
      - echo "Mounting Backup Drive..."
      - mountpoint -q /mnt/backup || mount /dev/sdc1 /mnt/backup
    after:
      - echo "Unmounting Backup Drive..."
      - umount /mnt/backup
    failure:
      - echo "Backup Failed! Unmounting..."
      - umount /mnt/backup

locations:
  my-data:
    from: /mnt/storage/data
    to: backup-hdd
    options:
      forget:
        keep-last: 7
        keep-daily: 7
        keep-weekly: 4
        keep-monthly: 6

  docker-data:
    from: /mnt/storage/docker
    to: backup-hdd
    hooks:
      before:
        - echo "Generating list of containers to stop..."
        # 1. Get running containers
        # 2. Exclude pihole/autorestic
        # 3. Save to file
        - docker ps --format '{{.Names}}' | grep -vE '^(pihole|autorestic)$' > /tmp/backup_containers.list
        
        - echo "Stopping containers found in list..."
        - if [ -s /tmp/backup_containers.list ]; then docker stop $(cat /tmp/backup_containers.list); fi
      
      after:
        - echo "Restarting containers (Attempt 1)..."
        # The '|| true' ensures the script doesn't crash if qbittorrent fails on the first try
        - if [ -s /tmp/backup_containers.list ]; then docker start $(cat /tmp/backup_containers.list) || true; fi
        
        - echo "Waiting for network stacks to initialize..."
        - sleep 5
        
        - echo "Restarting containers (Attempt 2 - Cleanup)..."
        # This second run picks up containers (like qbittorrent) that failed because gluetun wasn't ready yet
        - if [ -s /tmp/backup_containers.list ]; then docker start $(cat /tmp/backup_containers.list); fi
        
        - rm -f /tmp/backup_containers.list
      
      failure:
        - echo "Backup Failed! Restarting containers..."
        # Same double-start logic for failure mode
        - if [ -s /tmp/backup_containers.list ]; then docker start $(cat /tmp/backup_containers.list) || true; fi
        - sleep 5
        - if [ -s /tmp/backup_containers.list ]; then docker start $(cat /tmp/backup_containers.list); fi
        - rm -f /tmp/backup_containers.list

    options:
      forget:
        keep-last: 7
        keep-daily: 7
        keep-weekly: 4

  secrets:
    from: /home/tim/coding/homelab/.env
    to: backup-hdd
    options:
      forget:
        keep-last: 10