services:
  seerr:
    container_name: seerr
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    env_file: ./.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/dockerdata/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
    name: caddy_network
